DELETE FROM Feature_YieldChanges;

INSERT INTO Feature_YieldChanges
	(FeatureType, YieldType, Yield)
VALUES
	-- not a real feature, for Civilopedia only
	('FEATURE_LAKE', 'YIELD_FOOD', 3),
	('FEATURE_LAKE', 'YIELD_PRODUCTION', 1),

	('FEATURE_FALLOUT', 'YIELD_FOOD', -3),
	('FEATURE_FALLOUT', 'YIELD_PRODUCTION', -3),
	('FEATURE_FALLOUT', 'YIELD_GOLD', -3),

	('FEATURE_ATOLL', 'YIELD_PRODUCTION', 2),
	('FEATURE_ATOLL', 'YIELD_FOOD', 2),
	('FEATURE_FLOOD_PLAINS', 'YIELD_FOOD', 3),
	('FEATURE_FLOOD_PLAINS', 'YIELD_PRODUCTION', -1),
	('FEATURE_FOREST', 'YIELD_PRODUCTION', 1),
	('FEATURE_JUNGLE', 'YIELD_FOOD', 1),
	('FEATURE_MARSH', 'YIELD_FOOD', 1),
	('FEATURE_OASIS', 'YIELD_FOOD', 3),
	('FEATURE_OASIS', 'YIELD_GOLD', 2),
	('FEATURE_OASIS', 'YIELD_PRODUCTION', -1),

	-- Natural Wonder base yields
	('FEATURE_POTOSI', 'YIELD_PRODUCTION', 5),
	('FEATURE_EL_DORADO', 'YIELD_CULTURE', 5),
	('FEATURE_EL_DORADO', 'YIELD_GOLD', 5),
	('FEATURE_EL_DORADO', 'YIELD_GOLDEN_AGE_POINTS', 500),
	('FEATURE_FOUNTAIN_YOUTH', 'YIELD_SCIENCE', 5),
	('FEATURE_FOUNTAIN_YOUTH', 'YIELD_CULTURE', 5),
	('FEATURE_SOLOMONS_MINES', 'YIELD_PRODUCTION', 10),
	('FEATURE_VOLCANO', 'YIELD_SCIENCE', 10),
	('FEATURE_LAKE_VICTORIA', 'YIELD_FOOD', 10),
	('FEATURE_FUJI', 'YIELD_CULTURE', 5),
	('FEATURE_FUJI', 'YIELD_GOLD', 5),
	('FEATURE_FUJI', 'YIELD_SCIENCE', 5),
	('FEATURE_MT_KAILASH', 'YIELD_FAITH', 10),
	('FEATURE_KILIMANJARO', 'YIELD_CULTURE', 10),
	('FEATURE_MT_SINAI', 'YIELD_FAITH', 10),
	('FEATURE_GEYSER', 'YIELD_CULTURE', 5),
	('FEATURE_GEYSER', 'YIELD_SCIENCE', 5),
	('FEATURE_GIBRALTAR', 'YIELD_GOLD', 5),
	('FEATURE_SRI_PADA', 'YIELD_FOOD', 5),
	('FEATURE_CRATER', 'YIELD_SCIENCE', 5),
	('FEATURE_MESA', 'YIELD_FOOD', 5),
	('FEATURE_REEF', 'YIELD_SCIENCE', 5),
	('FEATURE_REEF', 'YIELD_FOOD', 5),
	('FEATURE_REEF', 'YIELD_CULTURE', 5),
	('FEATURE_ULURU', 'YIELD_PRODUCTION', 5);
